export type SeedCountry = { code: string; name: string; dialCode: string };

export const COUNTRIES_SEED: SeedCountry[] = [
  { code: "AF", name: "Afghanistan", dialCode: "+93" },
  { code: "ZA", name: "Afrique du Sud", dialCode: "+27" },
  { code: "AL", name: "Albanie", dialCode: "+355" },
  { code: "DZ", name: "Algérie", dialCode: "+213" },
  { code: "DE", name: "Allemagne", dialCode: "+49" },
  { code: "AD", name: "Andorre", dialCode: "+376" },
  { code: "AO", name: "Angola", dialCode: "+244" },
  { code: "AG", name: "Antigua-et-Barbuda", dialCode: "+1268" },
  { code: "SA", name: "Arabie saoudite", dialCode: "+966" },
  { code: "AR", name: "Argentine", dialCode: "+54" },
  { code: "AM", name: "Arménie", dialCode: "+374" },
  { code: "AU", name: "Australie", dialCode: "+61" },
  { code: "AT", name: "Autriche", dialCode: "+43" },
  { code: "AZ", name: "Azerbaïdjan", dialCode: "+994" },
  { code: "BS", name: "Bahamas", dialCode: "+1242" },
  { code: "BH", name: "Bahreïn", dialCode: "+973" },
  { code: "BD", name: "Bangladesh", dialCode: "+880" },
  { code: "BB", name: "Barbade", dialCode: "+1246" },
  { code: "BE", name: "Belgique", dialCode: "+32" },
  { code: "BZ", name: "Belize", dialCode: "+501" },
  { code: "BJ", name: "Bénin", dialCode: "+229" },
  { code: "BT", name: "Bhoutan", dialCode: "+975" },
  { code: "BY", name: "Biélorussie", dialCode: "+375" },
  { code: "MM", name: "Birmanie (Myanmar)", dialCode: "+95" },
  { code: "BO", name: "Bolivie", dialCode: "+591" },
  { code: "BA", name: "Bosnie-Herzégovine", dialCode: "+387" },
  { code: "BW", name: "Botswana", dialCode: "+267" },
  { code: "BR", name: "Brésil", dialCode: "+55" },
  { code: "BN", name: "Brunei", dialCode: "+673" },
  { code: "BG", name: "Bulgarie", dialCode: "+359" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226" },
  { code: "BI", name: "Burundi", dialCode: "+257" },
  { code: "KH", name: "Cambodge", dialCode: "+855" },
  { code: "CM", name: "Cameroun", dialCode: "+237" },
  { code: "CA", name: "Canada", dialCode: "+1" },
  { code: "CV", name: "Cap-Vert", dialCode: "+238" },
  { code: "CL", name: "Chili", dialCode: "+56" },
  { code: "CN", name: "Chine", dialCode: "+86" },
  { code: "CY", name: "Chypre", dialCode: "+357" },
  { code: "CO", name: "Colombie", dialCode: "+57" },
  { code: "KM", name: "Comores", dialCode: "+269" },
  { code: "CG", name: "Congo-Brazzaville", dialCode: "+242" },
  { code: "CD", name: "Congo (RDC)", dialCode: "+243" },
  { code: "KR", name: "Corée du Sud", dialCode: "+82" },
  { code: "KP", name: "Corée du Nord", dialCode: "+850" },
  { code: "CR", name: "Costa Rica", dialCode: "+506" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225" },
  { code: "HR", name: "Croatie", dialCode: "+385" },
  { code: "CU", name: "Cuba", dialCode: "+53" },
  { code: "DK", name: "Danemark", dialCode: "+45" },
  { code: "DJ", name: "Djibouti", dialCode: "+253" },
  { code: "DM", name: "Dominique", dialCode: "+1767" },
  { code: "EG", name: "Égypte", dialCode: "+20" },
  { code: "SV", name: "El Salvador", dialCode: "+503" },
  { code: "AE", name: "Émirats arabes unis", dialCode: "+971" },
  { code: "EC", name: "Équateur", dialCode: "+593" },
  { code: "ER", name: "Érythrée", dialCode: "+291" },
  { code: "ES", name: "Espagne", dialCode: "+34" },
  { code: "EE", name: "Estonie", dialCode: "+372" },
  { code: "SZ", name: "Eswatini", dialCode: "+268" },
  { code: "US", name: "États-Unis", dialCode: "+1" },
  { code: "ET", name: "Éthiopie", dialCode: "+251" },
  { code: "FJ", name: "Fidji", dialCode: "+679" },
  { code: "FI", name: "Finlande", dialCode: "+358" },
  { code: "FR", name: "France", dialCode: "+33" },
  { code: "GA", name: "Gabon", dialCode: "+241" },
  { code: "GM", name: "Gambie", dialCode: "+220" },
  { code: "GE", name: "Géorgie", dialCode: "+995" },
  { code: "GH", name: "Ghana", dialCode: "+233" },
  { code: "GR", name: "Grèce", dialCode: "+30" },
  { code: "GD", name: "Grenade", dialCode: "+1473" },
  { code: "GT", name: "Guatemala", dialCode: "+502" },
  { code: "GN", name: "Guinée", dialCode: "+224" },
  { code: "GW", name: "Guinée-Bissau", dialCode: "+245" },
  { code: "GQ", name: "Guinée équatoriale", dialCode: "+240" },
  { code: "GY", name: "Guyana", dialCode: "+592" },
  { code: "HT", name: "Haïti", dialCode: "+509" },
  { code: "HN", name: "Honduras", dialCode: "+504" },
  { code: "HU", name: "Hongrie", dialCode: "+36" },
  { code: "IN", name: "Inde", dialCode: "+91" },
  { code: "ID", name: "Indonésie", dialCode: "+62" },
  { code: "IQ", name: "Irak", dialCode: "+964" },
  { code: "IR", name: "Iran", dialCode: "+98" },
  { code: "IE", name: "Irlande", dialCode: "+353" },
  { code: "IS", name: "Islande", dialCode: "+354" },
  { code: "IL", name: "Israël", dialCode: "+972" },
  { code: "IT", name: "Italie", dialCode: "+39" },
  { code: "JM", name: "Jamaïque", dialCode: "+1876" },
  { code: "JP", name: "Japon", dialCode: "+81" },
  { code: "JO", name: "Jordanie", dialCode: "+962" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7" },
  { code: "KE", name: "Kenya", dialCode: "+254" },
  { code: "KG", name: "Kirghizistan", dialCode: "+996" },
  { code: "KI", name: "Kiribati", dialCode: "+686" },
  { code: "KW", name: "Koweït", dialCode: "+965" },
  { code: "LA", name: "Laos", dialCode: "+856" },
  { code: "LS", name: "Lesotho", dialCode: "+266" },
  { code: "LV", name: "Lettonie", dialCode: "+371" },
  { code: "LB", name: "Liban", dialCode: "+961" },
  { code: "LR", name: "Libéria", dialCode: "+231" },
  { code: "LY", name: "Libye", dialCode: "+218" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423" },
  { code: "LT", name: "Lituanie", dialCode: "+370" },
  { code: "LU", name: "Luxembourg", dialCode: "+352" },
  { code: "MK", name: "Macédoine du Nord", dialCode: "+389" },
  { code: "MG", name: "Madagascar", dialCode: "+261" },
  { code: "MY", name: "Malaisie", dialCode: "+60" },
  { code: "MW", name: "Malawi", dialCode: "+265" },
  { code: "MV", name: "Maldives", dialCode: "+960" },
  { code: "ML", name: "Mali", dialCode: "+223" },
  { code: "MT", name: "Malte", dialCode: "+356" },
  { code: "MA", name: "Maroc", dialCode: "+212" },
  { code: "MH", name: "Marshall (Îles)", dialCode: "+692" },
  { code: "MU", name: "Maurice", dialCode: "+230" },
  { code: "MR", name: "Mauritanie", dialCode: "+222" },
  { code: "MX", name: "Mexique", dialCode: "+52" },
  { code: "FM", name: "Micronésie", dialCode: "+691" },
  { code: "MD", name: "Moldavie", dialCode: "+373" },
  { code: "MC", name: "Monaco", dialCode: "+377" },
  { code: "MN", name: "Mongolie", dialCode: "+976" },
  { code: "ME", name: "Monténégro", dialCode: "+382" },
  { code: "MZ", name: "Mozambique", dialCode: "+258" },
  { code: "NA", name: "Namibie", dialCode: "+264" },
  { code: "NR", name: "Nauru", dialCode: "+674" },
  { code: "NP", name: "Népal", dialCode: "+977" },
  { code: "NI", name: "Nicaragua", dialCode: "+505" },
  { code: "NE", name: "Niger", dialCode: "+227" },
  { code: "NG", name: "Nigéria", dialCode: "+234" },
  { code: "NO", name: "Norvège", dialCode: "+47" },
  { code: "NZ", name: "Nouvelle-Zélande", dialCode: "+64" },
  { code: "OM", name: "Oman", dialCode: "+968" },
  { code: "UG", name: "Ouganda", dialCode: "+256" },
  { code: "UZ", name: "Ouzbékistan", dialCode: "+998" },
  { code: "PK", name: "Pakistan", dialCode: "+92" },
  { code: "PW", name: "Palaos", dialCode: "+680" },
  { code: "PS", name: "Palestine", dialCode: "+970" },
  { code: "PA", name: "Panama", dialCode: "+507" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", dialCode: "+675" },
  { code: "PY", name: "Paraguay", dialCode: "+595" },
  { code: "NL", name: "Pays-Bas", dialCode: "+31" },
  { code: "PE", name: "Pérou", dialCode: "+51" },
  { code: "PH", name: "Philippines", dialCode: "+63" },
  { code: "PL", name: "Pologne", dialCode: "+48" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "QA", name: "Qatar", dialCode: "+974" },
  { code: "RO", name: "Roumanie", dialCode: "+40" },
  { code: "GB", name: "Royaume-Uni", dialCode: "+44" },
  { code: "RU", name: "Russie", dialCode: "+7" },
  { code: "RW", name: "Rwanda", dialCode: "+250" },
  { code: "KN", name: "Saint-Christophe-et-Niévès", dialCode: "+1869" },
  { code: "SM", name: "Saint-Marin", dialCode: "+378" },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines", dialCode: "+1784" },
  { code: "LC", name: "Sainte-Lucie", dialCode: "+1758" },
  { code: "SB", name: "Salomon (Îles)", dialCode: "+677" },
  { code: "WS", name: "Samoa", dialCode: "+685" },
  { code: "ST", name: "Sao Tomé-et-Principe", dialCode: "+239" },
  { code: "SN", name: "Sénégal", dialCode: "+221" },
  { code: "RS", name: "Serbie", dialCode: "+381" },
  { code: "SC", name: "Seychelles", dialCode: "+248" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232" },
  { code: "SG", name: "Singapour", dialCode: "+65" },
  { code: "SK", name: "Slovaquie", dialCode: "+421" },
  { code: "SI", name: "Slovénie", dialCode: "+386" },
  { code: "SO", name: "Somalie", dialCode: "+252" },
  { code: "SD", name: "Soudan", dialCode: "+249" },
  { code: "SS", name: "Soudan du Sud", dialCode: "+211" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94" },
  { code: "SE", name: "Suède", dialCode: "+46" },
  { code: "CH", name: "Suisse", dialCode: "+41" },
  { code: "SR", name: "Suriname", dialCode: "+597" },
  { code: "SY", name: "Syrie", dialCode: "+963" },
  { code: "TJ", name: "Tadjikistan", dialCode: "+992" },
  { code: "TZ", name: "Tanzanie", dialCode: "+255" },
  { code: "TD", name: "Tchad", dialCode: "+235" },
  { code: "CZ", name: "Tchéquie", dialCode: "+420" },
  { code: "TH", name: "Thaïlande", dialCode: "+66" },
  { code: "TL", name: "Timor oriental", dialCode: "+670" },
  { code: "TG", name: "Togo", dialCode: "+228" },
  { code: "TO", name: "Tonga", dialCode: "+676" },
  { code: "TT", name: "Trinité-et-Tobago", dialCode: "+1868" },
  { code: "TN", name: "Tunisie", dialCode: "+216" },
  { code: "TM", name: "Turkménistan", dialCode: "+993" },
  { code: "TR", name: "Turquie", dialCode: "+90" },
  { code: "TV", name: "Tuvalu", dialCode: "+688" },
  { code: "UA", name: "Ukraine", dialCode: "+380" },
  { code: "UY", name: "Uruguay", dialCode: "+598" },
  { code: "VU", name: "Vanuatu", dialCode: "+678" },
  { code: "VA", name: "Vatican", dialCode: "+379" },
  { code: "VE", name: "Venezuela", dialCode: "+58" },
  { code: "VN", name: "Vietnam", dialCode: "+84" },
  { code: "YE", name: "Yémen", dialCode: "+967" },
  { code: "ZM", name: "Zambie", dialCode: "+260" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263" },
];
