// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/client-home/Modern.tsx": () => import("../components/mockups/client-home/Modern.tsx"),
  "./components/mockups/client-home/Premium.tsx": () => import("../components/mockups/client-home/Premium.tsx"),
  "./components/mockups/client-home/Urban.tsx": () => import("../components/mockups/client-home/Urban.tsx")
};
